### PR TITLE
new preProcesing

### PR DESCRIPTION
**Pull request by Ragansu**
This PR removed computing derived quantities from the preProcessing as its already taken care of in the systematics script. 

Along with that it also removed cuts on `mT_lep_had`.
RC

### CODE REVIEW

**Comment by Ragansu** [comment]
Since It need root and DELPHES, I haven't tested it. I will notify here and in slack when its ready for review.

**Comment by Ragansu** [comment]
In order to not have 2 different version of systematics and cuts I have added the main HEP-Competition repo as submodule and called it in here.

**Comment by cjh1** [comment]
@Ragansu This seems to be pulling in a bunch of old commits ( from months ago ) ?

**Comment by Ragansu** [comment]
Yeah this PR is ancient. It never got reviewed so it stayed there and I kept building in top of it when I found bugs.

**Pull request merged**
